---
title: 'Q1: Are lake and terrestrial primary productivity coherent?'
author: "Jonathan Walter, Grace Wilkinson, Rachel Fleck, Michael Pace"
date: "4/17/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(aqts)
library(wsyn)
library(rgdal)
library(LAGOSNE)
library(raster)
library(MuMIn)
library(dplyr)
library(nlme)
library(lmerTest)
library(viridis)
library(fields)
#library(partykit)
library(pdp)
library(party)
library(spatstat)

rm(list=ls())

```

This document organizes for openness and reproducibility analyses of the temporal coherence of interannual variation in lake primary productivity with terrestrial primary productivity in the landscape surrounding the lake.

# Data import

Data produced in 'ms1_prep.Rmd' are loaded.

```{r load workspace, echo=TRUE, cache=FALSE}

load("/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/RData files/ms1_analysis_inprogress1.RData")

```

```{r examine missing values, echo=TRUE, cache=FALSE}
any(sapply(analysislakes$lakedata, function(x){any(is.infinite(x))}))
any(sapply(analysislakes$lakedata, function(x){any(is.na(x))}))
which(sapply(analysislakes$lakedata, function(x){any(is.na(x))}))
analysislakes$lakeinfo[which(sapply(analysislakes$lakedata, function(x){any(is.na(x))})),]

# image(accndvi)
# points(lakepts.prj[which(sapply(analysislakes$lakedata, function(x){any(is.na(x))})),])

dbuff[which(sapply(analysislakes$lakedata, function(x){any(is.na(x))}))]

analysislakes$lakeinfo<-analysislakes$lakeinfo[!sapply(analysislakes$lakedata, function(x){any(is.na(x))}),]
analysislakes$lakedata<-analysislakes$lakedata[!sapply(analysislakes$lakedata, function(x){any(is.na(x))})]

analysislakes$lakeinfo$tslength<-analysislakes$lakeinfo$end-analysislakes$lakeinfo$start+1
# analysislakes$lakedata<-analysislakes$lakedata[!analysislakes$lakeinfo$tslength < 20]
# analysislakes$lakeinfo<-analysislakes$lakeinfo[!analysislakes$lakeinfo$tslength < 20,]

```

```{r compute coherences, echo=TRUE, cache=FALSE}

source("~/GitHub/AquaTerrSynch/AnalysisCode/bandtest_coh.R")

tsranges<-rbind(c(2,4),c(4,Inf),c(2,Inf))

coh.chlaXaccndvi<-NULL
coh.chlaXmaxndvi<-NULL

for(lind in 1:length(analysislakes$lakedata)){
  lakedat.ii<-cleandat(analysislakes$lakedata[[lind]], as.numeric(colnames(analysislakes$lakedata[[lind]])), clev=5)$cdat
  chlaXaccndvi<-coh(lakedat.ii[1,], lakedat.ii[2,], as.numeric(colnames(analysislakes$lakedata[[lind]])),
                    norm="powall", sigmethod="fast", nrand=10000)
  chlaXmaxndvi<-coh(lakedat.ii[1,], lakedat.ii[3,], as.numeric(colnames(analysislakes$lakedata[[lind]])),
                    norm="powall", sigmethod="fast", nrand=10000)
  for(rind in 1:nrow(tsranges)){
    chlaXaccndvi<-bandtest.coh(chlaXaccndvi, tsranges[rind,])
    chlaXmaxndvi<-bandtest.coh(chlaXmaxndvi, tsranges[rind,])
  }
  coh.chlaXaccndvi<-rbind(coh.chlaXaccndvi, c(t(as.matrix(chlaXaccndvi$bandp[,3:5]))))
  coh.chlaXmaxndvi<-rbind(coh.chlaXmaxndvi, c(t(as.matrix(chlaXmaxndvi$bandp[,3:5]))))
  
}

coh.chlaXaccndvi<-as.data.frame(coh.chlaXaccndvi)
coh.chlaXmaxndvi<-as.data.frame(coh.chlaXmaxndvi)

colnames(coh.chlaXaccndvi)<-paste0("accndvi",c("p.ts1","phi.ts1","coh.ts1","p.ts2","phi.ts2","coh.ts2","p.ts3","phi.ts3","coh.ts3"))
colnames(coh.chlaXmaxndvi)<-paste0("maxndvi",c("p.ts1","phi.ts1","coh.ts1","p.ts2","phi.ts2","coh.ts2","p.ts3","phi.ts3","coh.ts3"))

coh.chlaXaccndvi$lagoslakeid<-analysislakes$lakeinfo$lagoslakeid
coh.chlaXmaxndvi$lagoslakeid<-analysislakes$lakeinfo$lagoslakeid

```

```{r summarize coherences, echo=TRUE, cache=FALSE}
#short timescales
hist(coh.chlaXaccndvi$accndvicoh.ts1, main="Accumulated NDVI, short timescales", xlab="Coherence", ylab="Frequency")
hist(coh.chlaXmaxndvi$maxndvicoh.ts1, main="Maximum NDVI, short timescales", xlab="Coherence", ylab="Frequency")

quantile(coh.chlaXaccndvi$accndvicoh.ts1)
quantile(coh.chlaXmaxndvi$maxndvicoh.ts1)

alpha=0.05
sum(coh.chlaXaccndvi$accndvip.ts1<alpha)/nrow(coh.chlaXaccndvi)
sum(coh.chlaXmaxndvi$maxndvip.ts1<alpha)/nrow(coh.chlaXmaxndvi)

print(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<alpha]/pi) #only pattern is that lakes don't lead the landscape
print(coh.chlaXmaxndvi$maxndviphi.ts1[coh.chlaXmaxndvi$maxndvip.ts1<alpha]/pi)

phicls<-c(-1,-.75,-0.25,0.25,0.75,1)

# hist(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<0.2]/pi, main="Accumulated NDVI, short timescales", xlab="Phase (pi)", ylab="Frequency", breaks=phicls)
rose(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<0.3], unit="radian",
     breaks=seq(0,2*pi,length.out=16))
#hist(coh.chlaXmaxndvi$maxndviphi.ts1[coh.chlaXmaxndvi$maxndvip.ts1<0.2]/pi, main="Maximum NDVI, short timescales", xlab="Phase (pi)", ylab="Frequency", breaks=5)

#long timescales
hist(coh.chlaXaccndvi$accndvicoh.ts2, main="Accumulated NDVI, long timescales", xlab="Coherence", ylab="Frequency")
hist(coh.chlaXmaxndvi$maxndvicoh.ts2, main="Maximum NDVI, long timescales", xlab="Coherence", ylab="Frequency")

quantile(coh.chlaXaccndvi$accndvicoh.ts2)
quantile(coh.chlaXmaxndvi$maxndvicoh.ts2)

alpha=0.05
sum(coh.chlaXaccndvi$accndvip.ts2<alpha)/nrow(coh.chlaXaccndvi)
sum(coh.chlaXmaxndvi$maxndvip.ts2<alpha)/nrow(coh.chlaXmaxndvi)

print(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<alpha]/pi)
print(coh.chlaXmaxndvi$maxndviphi.ts2[coh.chlaXmaxndvi$maxndvip.ts2<alpha]/pi)

# hist(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<0.2]/pi, main="Accumulated NDVI, long timescales", xlab="Phase (pi)", ylab="Frequency", breaks=phicls)
rose(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<0.3], unit="radian",
     breaks=seq(0,2*pi,length.out=16))

#hist(coh.chlaXmaxndvi$maxndviphi.ts1[coh.chlaXmaxndvi$maxndvicoh.ts2>0.6]/pi, main="Maximum NDVI, short timescales", xlab="Phase (pi)", ylab="Frequency", breaks=5)

```

```{r mapping, echo=TRUE, cache=FALSE}

states<-readOGR("~/Box Sync/NSF EAGER Synchrony/Data/statesp020.shp")
getstates<-c("Minnesota", "Iowa", "Wisconsin", "Illinois", "Missouri", "Michigan", "Indiana", "Ohio", "Pennsylvania", "New York", "New Jersey", "Connecticut", "New Hampshire", "Rhode Island", "Massachusetts", "Vermont", "Maine")
lagosstates<-states[states@data$STATE %in% getstates,]

plot(lagosstates, main="Lakes selected for analysis")
points(analysislakes$lakeinfo$nhd_long, analysislakes$lakeinfo$nhd_lat, pch=16, cex=1, col="blue")


cohplotdata<-left_join(analysislakes$lakeinfo, coh.chlaXaccndvi, by="lagoslakeid")

pal<-viridis(100)

par(mar=c(1,0,2,0))

plot(lagosstates, main="Lakes by short timescale coherence")
points(cohplotdata$nhd_long, cohplotdata$nhd_lat, pch=16, cex=1, col=pal[round(cohplotdata$accndvicoh.ts1,2)*100])
colorbar.plot(x=mean(par("usr")[1:2]),y=par("usr")[3],strip=1:100,col=pal,horizontal = T)

plot(lagosstates, main="Lakes by long timescale coherence")
points(cohplotdata$nhd_long, cohplotdata$nhd_lat, pch=16, cex=1, col=pal[round(cohplotdata$accndvicoh.ts2,2)*100])
colorbar.plot(x=mean(par("usr")[1:2]),y=par("usr")[3],strip=1:100,col=pal,horizontal = T)

```


```{r add vars for modelling, echo=TRUE, cache=FALSE}

#Need to add: depth, average growing season Chlorophyll-a, TSI(chla) categories, pct ag

#agriculture -- is 500m buffer best? Other options include 100m buffer (probably too small) and hu12 watershed
# pct.ag<-lagosne_select(table="buffer500m.lulc", vars=c("lagoslakeid","buffer500m_nlcd2001_pct_82","buffer500m_nlcd2006_pct_82","buffer500m_nlcd2011_pct_82"))
pct.ag<-lagosne_select(table="hu12.lulc", vars=c("hu12_zoneid","hu12_nlcd2001_pct_82","hu12_nlcd2006_pct_82","hu12_nlcd2011_pct_82"))
pct.ag<-pct.ag[pct.ag$hu12_zoneid %in% analysislakes$lakeinfo$hu12_zoneid,]
pct.ag.avg<-data.frame(hu12_zoneid=pct.ag$hu12_zoneid, pct.ag=rowMeans(pct.ag[,2:4]))

#Wetlands
pct.wetlands<-lagosne_select(table="hu12.lulc", vars=c(c("hu12_zoneid","hu12_nlcd2001_pct_90","hu12_nlcd2006_pct_90",
                                                         "hu12_nlcd2011_pct_90","hu12_nlcd2001_pct_95","hu12_nlcd2006_pct_95",
                                                         "hu12_nlcd2011_pct_95")))
pct.wetlands<-pct.wetlands[pct.wetlands$hu12_zoneid %in% analysislakes$lakeinfo$hu12_zoneid,]
pct.wetlands$sum2001<-rowSums(pct.wetlands[,c(2,5)])
pct.wetlands$sum2006<-rowSums(pct.wetlands[,c(3,6)])
pct.wetlands$sum2011<-rowSums(pct.wetlands[,c(4,7)])
pct.wetlands.avg<-data.frame(hu12_zoneid=pct.wetlands$hu12_zoneid, pct.wetlands=rowMeans(pct.wetlands[,8:10]))

#depth
depth<-lagosne_select(table="lakes_limno", vars=c("lagoslakeid","maxdepth"))
depth<-depth[depth$lagoslakeid %in% analysislakes$lakeinfo$lagoslakeid,] #use max depth because it's more complete

#growing season Chlorophyll-a
chla<-lagosne_select(table="epi_nutr", vars=c("lagoslakeid","samplemonth","chla"))
chla<-chla[chla$lagoslakeid %in% analysislakes$lakeinfo$lagoslakeid,]
gs.chla<-chla[chla$samplemonth %in% 5:9,]
avg.chla<-aggregate(chla ~ lagoslakeid, data=gs.chla, FUN=mean, na.rm=T)

#growing season DOC
doc<-lagosne_select(table="epi_nutr", vars=c("lagoslakeid","samplemonth","doc"))
doc<-doc[doc$lagoslakeid %in% analysislakes$lakeinfo$lagoslakeid,]
gs.doc<-doc[doc$samplemonth %in% 5:9,]
avg.doc<-aggregate(doc ~ lagoslakeid, data=gs.doc, FUN=mean, na.rm=T)

#Chlorophyll-a TSI class
#TSI(CHL) = 9.81 ln(CHL) + 30.6
tsi.chl<-data.frame(lagoslakeid=avg.chla$lagoslakeid, tsi=9.81 * log(avg.chla$chla) + 30.6)
tsi.chl$tsi.cat<-rep("lake",nrow(tsi.chl))

tsi.chl$tsi.cat[tsi.chl$tsi < 40]<-"oligotrophic"
tsi.chl$tsi.cat[tsi.chl$tsi >=40 & tsi.chl$tsi < 50]<-"mesotrophic"
tsi.chl$tsi.cat[tsi.chl$tsi >=50 & tsi.chl$tsi < 70]<-"eutrophic"
tsi.chl$tsi.cat[tsi.chl$tsi >= 70] <-"hypereutrophic"

#CV of terrestrial NDVI
cv.accndvi<-NULL
for(lake in 1:length(analysislakes$lakedata)){
  tmp<-analysislakes$lakedata[[lake]][rownames(analysislakes$lakedata[[lake]])=="accndvi",]
  cv.accndvi<-c(cv.accndvi, sd(tmp)/mean(tmp))  
 # rm(tmp)
}
cv.accndvi<-data.frame(lagoslakeid=as.numeric(names(analysislakes$lakedata)), cv.accndvi=cv.accndvi)

#mean precipitation
prcp.normal<-raster("~/Box Sync/NSF EAGER Synchrony/Data/PRISM Data/PRISM_ppt_30yr_normal_800mM2_annual_bil.bil")
lakepts<-SpatialPoints(coords=cbind(analysislakes$lakeinfo$nhd_long,analysislakes$lakeinfo$nhd_lat))
lake.prcp<-data.frame(lagoslakeid=analysislakes$lakeinfo$lagoslakeid, prcp.normal=raster::extract(prcp.normal,lakepts))

#huc2 and huc4 watershed codes
huc_codes<-read.csv("/Users/jonathanwalter/GitHub/AquaTerrSynch/AnalysisCode/match_huc_codes.csv", colClasses = 'character')

#state info
states<-lagosne_select(table="state", vars=c("state_zoneid","state_name"))

predictors<-analysislakes$lakeinfo
predictors<-left_join(predictors, depth, by="lagoslakeid")
predictors<-left_join(predictors, pct.ag.avg, by="hu12_zoneid")
predictors<-left_join(predictors, pct.wetlands.avg, by="hu12_zoneid")
predictors<-left_join(predictors, avg.chla, by="lagoslakeid")
predictors<-left_join(predictors, tsi.chl, by="lagoslakeid")
predictors<-left_join(predictors, states, by="state_zoneid")
predictors<-left_join(predictors, cv.accndvi, by="lagoslakeid")
predictors<-left_join(predictors, avg.doc, by="lagoslakeid")
predictors<-left_join(predictors, lake.prcp, by="lagoslakeid")
#predictors<-left_join(predictors, huc_codes, by="hu4_zoneid")

for(nn in 1:ncol(predictors)){
  
  if(is.factor(predictors[,nn])){
    predictors[,nn]<-factor(predictors[,nn])
  }
  
}
  
str(predictors)
hist(predictors$tslength)
hist(predictors$lake_area_ha)
hist(log10(predictors$lake_area_ha))
hist(predictors$lake_perim_meters)
hist(log10(predictors$lake_perim_meters))
table(predictors$nhd_fcode)
table(predictors$hu12_zoneid)
hist(predictors$elevation_m)
hist(predictors$maxdepth)
hist(log10(predictors$maxdepth))
hist(predictors$pct.ag)
hist(log10(predictors$pct.ag))
hist(predictors$chla)
hist(log10(predictors$chla))
hist(predictors$tsi)
table(predictors$tsi.cat)
hist(predictors$cv.accndvi)
hist(predictors$pct.wetlands)
hist(predictors$doc)
hist(predictors$prcp.normal)

# predictors$log10_lake_area_ha<-log10(predictors$lake_area_ha) #not necessary to transform with random forests
# predictors$log10_lake_perim_meters<-log10(predictors$lake_perim_meters)
# predictors$log10_maxdepth<-log10(predictors$maxdepth)
# predictors$log10_pct.ag<-log10(predictors$pct.ag+1)
# predictors$log10_chla<-log10(predictors$chla)

modvars.accndvi<-left_join(predictors, coh.chlaXaccndvi, by="lagoslakeid")
modvars.accndvi$nhd_ftype<-factor(modvars.accndvi$nhd_ftype)
modvars.accndvi$tsi.cat<-factor(modvars.accndvi$tsi.cat)
modvars.accndvi$tslength<-modvars.accndvi$end-modvars.accndvi$start + 1

modvars.accndvi<-modvars.accndvi[!is.na(modvars.accndvi$maxdepth),]
modvars.accndvi<-modvars.accndvi[!is.na(modvars.accndvi$pct.ag),]

modvars.accndvi.phist<-modvars.accndvi[modvars.accndvi$accndvip.ts1<0.3,]
modvars.accndvi.philt<-modvars.accndvi[modvars.accndvi$accndvip.ts2<0.3,]



```


```{r modellingCoherence, echo=TRUE, cache=FALSE}

# cforest.st<-partykit::cforest(accndvicoh.ts1 ~ lake_area_ha + lake_perim_meters + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + cv.accndvi, 
#                     data=modvars.accndvi, ntree=20000)
cforest.st<-party::cforest(accndvicoh.ts1 ~ lake_area_ha + lake_perim_meters + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + 
                             cv.accndvi + pct.wetlands + doc + prcp.normal,
                    data=modvars.accndvi, controls=cforest_control(ntree=80000))
predcoh.st<-predict(cforest.st, newdata=modvars.accndvi,type="response")
hist(predcoh.st)
hist(modvars.accndvi$accndvicoh.ts1)
plot(predcoh.st, modvars.accndvi$accndvicoh.ts1, xlab="predicted", ylab="empirical", main="Coherence, short ts",
     xlim=c(0,1), ylim=c(0,1))
abline(a=0,b=1)
cor.test(predcoh.st,modvars.accndvi$accndvicoh.ts1)
varimp.coh.st<-varimp(cforest.st)
print(varimp.coh.st[order(varimp.coh.st, decreasing=T)])


partial(cforest.st, pred.var="prcp.normal", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="lake_perim_meters", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="pct.ag", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="lake_area_ha", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="maxdepth", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="chla", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="doc", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="pct.wetlands", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="cv.accndvi", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="tsi.cat", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.st, pred.var="hu4_zoneid", train=modvars.accndvi, type="regression", plot=T)

cforest.lt<-party::cforest(accndvicoh.ts2 ~ lake_area_ha + lake_perim_meters + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + 
                             cv.accndvi+ pct.wetlands + doc + prcp.normal, 
                    data=modvars.accndvi, controls=cforest_control(ntree=80000))
predcoh.lt<-predict(cforest.lt, newdata=modvars.accndvi)
# hist(predcoh.lt)
# hist(modvars.accndvi$accndvicoh.ts2)
plot(predcoh.lt, modvars.accndvi$accndvicoh.ts2, xlab="predicted", ylab="empirical", main="Coherence, long st",
     xlim=c(0,1), ylim=c(0,1))
abline(a=0,b=1)
cor.test(predcoh.lt,modvars.accndvi$accndvicoh.ts2)
varimp.coh.lt<-varimp(cforest.lt)
print(varimp.coh.lt[order(varimp.coh.lt, decreasing=T)])


partial(cforest.lt, pred.var="pct.wetlands", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="cv.accndvi", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="hu4_zoneid", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="doc", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="lake_area_ha", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="lake_perim_meters", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="prcp.normal", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="chla", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="tsi.cat", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="pct.ag", train=modvars.accndvi, type="regression", plot=T)
partial(cforest.lt, pred.var="maxdepth", train=modvars.accndvi, type="regression", plot=T)

```

```{r modellingPhase, echo=TRUE, cache=FALSE}

cforest.phi.st<-cforest(cos(accndviphi.ts1) ~ lake_area_ha + lake_perim_meters + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + 
                          cv.accndvi+ pct.wetlands + doc + prcp.normal, 
                        data=modvars.accndvi.phist,controls=cforest_control(ntree=40000))
predphi.st<-predict(cforest.phi.st, newdata=modvars.accndvi.phist)
# hist(predphi.st)
# hist(cos(modvars.accndvi.phist$accndviphi.ts1))
plot(predphi.st, cos(modvars.accndvi.phist$accndviphi.ts1), xlab="predicted", ylab="empirical", main="cos(phase), short ts",
     xlim=c(-1,1), ylim=c(-1,1))
abline(a=0,b=1)
cor.test(predphi.st,cos(modvars.accndvi.phist$accndviphi.ts1))
varimp.phi.st<-varimp(cforest.phi.st)
print(varimp.phi.st[order(varimp.phi.st,decreasing=TRUE)])

partial(cforest.phi.st, pred.var="maxdepth", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="lake_area_ha", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="lake_perim_meters", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="doc", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="cv.accndvi", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="pct.wetlands", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="prcp.normal", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="chla", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="pct.ag", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="tsi.cat", train=modvars.accndvi.phist, type="regression", plot=T)
partial(cforest.phi.st, pred.var="hu4_zoneid", train=modvars.accndvi.phist, type="regression", plot=T)


cforest.phi.lt<-cforest(cos(accndviphi.ts2) ~ lake_area_ha + lake_perim_meters + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + 
                          cv.accndvi + pct.wetlands + doc + prcp.normal, 
                        data=modvars.accndvi.philt,controls=cforest_control(ntree=40000))
predphi.lt<-predict(cforest.phi.lt, newdata=modvars.accndvi.philt)
# hist(predphi.lt)
# hist(cos(modvars.accndvi.philt$accndviphi.ts2))
plot(predphi.lt, cos(modvars.accndvi.philt$accndviphi.ts2), xlab="predicted", ylab="empirical", main="cos(phase), short ts",
     xlim=c(-1,1), ylim=c(-1,1))
abline(a=0,b=1)
cor.test(predphi.lt,cos(modvars.accndvi.philt$accndviphi.ts2))
varimp.phi.lt<-varimp(cforest.phi.lt)
print(varimp.phi.lt[order(varimp.phi.lt, decreasing=TRUE)])

partial(cforest.phi.lt, pred.var="hu4_zoneid", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="lake_area_ha", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="prcp.normal", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="pct.wetlands", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="lake_perim_meters", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="doc", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="chla", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="cv.accndvi", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="maxdepth", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="pct.ag", train=modvars.accndvi.philt, type="regression", plot=T)
partial(cforest.phi.lt, pred.var="tsi.cat", train=modvars.accndvi.philt, type="regression", plot=T)

```

