---
title: 'Q1: Are lake and terrestrial primary productivity coherent?'
author: "Jonathan Walter, Grace Wilkinson, Rachel Fleck, Michael Pace"
date: "4/17/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(aqts)
library(wsyn)
library(rgdal)
library(LAGOSNE)
library(raster)
library(MuMIn)
library(dplyr)
library(nlme)

rm(list=ls())

```

This document organizes for openness and reproducibility analyses of the temporal coherence of interannual variation in lake primary productivity with terrestrial primary productivity in the landscape surrounding the lake.

# Data important and formatting

```{r limno import and formatting, echo=TRUE, cache=FALSE}

##updated cleanAnnualts on 5/5/19

lakes_to_get<-read.csv("~/GitHub/AquaTerrSynch/AnalysisCode/lakes20yrs_chla.csv")$x

lagoslakes.raw<-makeLAGOSannualts(lakes_to_get, infovars=c("lake_area_ha", "lake_perim_meters", "nhd_ftype", "nhd_fcode", "hu4_zoneid", 
                                                           "hu12_zoneid", "state_zoneid", "elevation_m"), tsvars=c("chla"), 
                                  minmos=3, minobs=3, timespan=c(1989,2018),lagosversion="1.087.3")
lagoslakes.cln<-cleanAnnualts(lagoslakes.raw)

rm(lakes_to_get)

MNMPCAlakes.raw<-makeMNMPCAannualts(dir="/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/LAGOS Extended/MN_MPCA",
                                   infovars=c("lake_area_ha", "lake_perim_meters", "nhd_ftype", "nhd_fcode", "hu4_zoneid","hu12_zoneid", 
                                              "state_zoneid", 
                                              "elevation_m"), minmos=3, minobs=3, timespan=c(1989,2018))
MNMPCAlakes.raw<-fixNamestoLAGOS(MNMPCAlakes.raw,"Minnesota MPCA")
MNMPCAlakes.cln<-cleanAnnualts(MNMPCAlakes.raw)

WIDNRlakes.raw<-makeWIDNRannualts(dir="/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/LAGOS Extended/WI_DNR",
                                  infovars=c("lake_area_ha", "lake_perim_meters", "nhd_ftype", "nhd_fcode", "hu4_zoneid","hu12_zoneid", 
                                             "state_zoneid", 
                                             "elevation_m"), minmos=3, minobs=3, timespan=c(1989,2018))
WIDNRlakes.raw<-fixNamestoLAGOS(WIDNRlakes.raw, "Wisconsin DNR")
WIDNRlakes.cln<-cleanAnnualts(WIDNRlakes.raw)

#IowaALMlakes<-makeIowaALMannualts(almdat="/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/Iowa Synchrony Lakes.csv")

analysislakes<-list(lakeinfo=rbind(lagoslakes.cln$lakeinfo,MNMPCAlakes.cln$lakeinfo,WIDNRlakes.cln$lakeinfo),
                    lakedata=c(lagoslakes.cln$lakedata, MNMPCAlakes.cln$lakedata, WIDNRlakes.cln$lakedata))

any(duplicated(analysislakes$lakeinfo$lagoslakeid)) #no duplicates

```

```{r AVHRR data import, echo=FALSE, cache=FALSE}

dbuff<-calcBufferDist(sa=analysislakes$lakeinfo$lake_area_ha, ltype=analysislakes$lakeinfo$nhd_ftype, minbuff=2500)

accndvi<-stack("/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/SatelliteData/accvi1989_2018.img")
maxndvi<-stack("/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/SatelliteData/mxvi1989_2018.img")

nlcdwater<-raster("/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/SatelliteData/landcover/nlcd2011_cls11.img")
watermask<-nlcdwater<0.05

accndvi<-mask(accndvi,watermask,maskvalue=0) #mask out pixels that have too much water in them
maxndvi<-mask(maxndvi,watermask,maskvalue=0)

analysislakes<-addAVHRRannualts(analysislakes, accndvi, dbuff)
analysislakes<-addAVHRRannualts(analysislakes, maxndvi, dbuff)

save.image("/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/RData files/ms1_analysis_inprogress1_v10873.RData")

```
