---
title: 'Q1: Are lake and terrestrial primary productivity coherent?'
author: "Jonathan Walter, Grace Wilkinson, Rachel Fleck, Michael Pace"
date: "4/17/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(aqts)
library(wsyn)
library(rgdal)
library(LAGOSNE)
library(raster)
library(MuMIn)
library(dplyr)
library(nlme)
library(lmerTest)
library(viridis)
library(fields)
#library(partykit)
# library(pdp)
# library(party)
library(mgcv)
library(MuMIn)
library(spatstat)

rm(list=ls())

```

This document organizes for openness and reproducibility analyses of the temporal coherence of interannual variation in lake primary productivity with terrestrial primary productivity in the landscape surrounding the lake.

# Data import

Data produced in 'ms1_prep.Rmd' are loaded.

```{r load workspace, echo=TRUE, cache=FALSE}

load("/Users/jonathanwalter/Box Sync/NSF EAGER Synchrony/Data/RData files/ms1_analysis_inprogress1_v10873.RData")

```

```{r examine missing values, echo=TRUE, cache=FALSE}
any(sapply(analysislakes$lakedata, function(x){any(is.infinite(x))}))
any(sapply(analysislakes$lakedata, function(x){any(is.na(x))}))
which(sapply(analysislakes$lakedata, function(x){any(is.na(x))}))
analysislakes$lakeinfo[which(sapply(analysislakes$lakedata, function(x){any(is.na(x))})),]

# image(accndvi)
# points(lakepts.prj[which(sapply(analysislakes$lakedata, function(x){any(is.na(x))})),])

dbuff[which(sapply(analysislakes$lakedata, function(x){any(is.na(x))}))]

analysislakes$lakeinfo<-analysislakes$lakeinfo[!sapply(analysislakes$lakedata, function(x){any(is.na(x))}),]
analysislakes$lakedata<-analysislakes$lakedata[!sapply(analysislakes$lakedata, function(x){any(is.na(x))})]

analysislakes$lakeinfo$tslength<-analysislakes$lakeinfo$end-analysislakes$lakeinfo$start+1
# analysislakes$lakedata<-analysislakes$lakedata[!analysislakes$lakeinfo$tslength < 20]
# analysislakes$lakeinfo<-analysislakes$lakeinfo[!analysislakes$lakeinfo$tslength < 20,]

```

```{r compute coherences, echo=TRUE, cache=FALSE}

source("~/GitHub/AquaTerrSynch/AnalysisCode/bandtest_coh.R")

tsranges<-rbind(c(2,4),c(4,Inf),c(2,Inf))

coh.chlaXaccndvi<-NULL
#coh.chlaXmaxndvi<-NULL

for(lind in 1:length(analysislakes$lakedata)){
  lakedat.ii<-cleandat(analysislakes$lakedata[[lind]], as.numeric(colnames(analysislakes$lakedata[[lind]])), clev=5)$cdat
  chlaXaccndvi<-coh(lakedat.ii[1,], lakedat.ii[2,], as.numeric(colnames(analysislakes$lakedata[[lind]])),
                    norm="powall", sigmethod="fast", nrand=10000)
#  chlaXmaxndvi<-coh(lakedat.ii[1,], lakedat.ii[3,], as.numeric(colnames(analysislakes$lakedata[[lind]])),
#                    norm="powall", sigmethod="fast", nrand=10000)
  for(rind in 1:nrow(tsranges)){
    chlaXaccndvi<-bandtest.coh(chlaXaccndvi, tsranges[rind,])
    #chlaXmaxndvi<-bandtest.coh(chlaXmaxndvi, tsranges[rind,])
  }
  coh.chlaXaccndvi<-rbind(coh.chlaXaccndvi, c(t(as.matrix(chlaXaccndvi$bandp[,3:5]))))
#  coh.chlaXmaxndvi<-rbind(coh.chlaXmaxndvi, c(t(as.matrix(chlaXmaxndvi$bandp[,3:5]))))
  
}

coh.chlaXaccndvi<-as.data.frame(coh.chlaXaccndvi)
#coh.chlaXmaxndvi<-as.data.frame(coh.chlaXmaxndvi)

colnames(coh.chlaXaccndvi)<-paste0("accndvi",c("p.ts1","phi.ts1","coh.ts1","p.ts2","phi.ts2","coh.ts2","p.ts3","phi.ts3","coh.ts3"))
#colnames(coh.chlaXmaxndvi)<-paste0("maxndvi",c("p.ts1","phi.ts1","coh.ts1","p.ts2","phi.ts2","coh.ts2","p.ts3","phi.ts3","coh.ts3"))

coh.chlaXaccndvi$lagoslakeid<-analysislakes$lakeinfo$lagoslakeid
#coh.chlaXmaxndvi$lagoslakeid<-analysislakes$lakeinfo$lagoslakeid

```

```{r pedagogical example, echo=TRUE, cache=FALSE}
#looking for especially coherent lakes did not return easy-to-interpret examples. Proceeding with simulated data

tmax=50
res=0.1
tt=seq(1,tmax,res)

p1<-2
sig1<-sin(seq(0,2*pi*tmax/p1,length.out=length(tt)))
p2<-10
sig2<-sin(seq(0,2*pi*tmax/p2,length.out=length(tt)))

comb1<-sig1+0.7*sig2+3.5
comb2<-sig1+-0.7*sig2


laymat<-matrix(1,nrow=2,ncol=3)
laymat[2,]<-2:4

sig3<-sig2[tt<=20]
sig4<-sig3*0.9
sig5<-sin(seq(-pi/2,2*pi*20/p2-(pi/2),length.out=length(tt[tt<=20])))
sig6<-sig3*-1

# tiff("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig1_pedagogical.tif", units="in",
#      res=300, width=6.5, height=4)
# 
# layout(laymat)
# par(mar=c(1.5,1.5,2,1.5), mgp=c(1,1,0), oma=c(2,2,0,0))
# 
# plot(NA,NA,ylim=c(-2,5.2),xlim=range(tt), xlab="", ylab="", xaxt="n",yaxt="n")
# lines(tt,comb1,lwd=2)
# lines(tt,comb2,lwd=2,col="red")
# axis(1, at=c(0,10,20,30,40,50),labels=NA)
# axis(2, at=c(-1,1.5,4), labels=NA)
# mtext("Timescale specific relationship",3,line=0.25)
# text(0.4,4.9,"a)",cex=1.2)
# 
# plot(NA,NA,ylim=c(-1,1),xlim=c(0,20),xaxt="n",yaxt="n",xlab="",ylab="")
# axis(1, at=c(0,10,20), labels=NA)
# axis(2, at=c(-1,0,1), labels=NA)
# lines(tt[tt<=20],sig3,lwd=2)
# lines(tt[tt<=20],sig4,lwd=2,col="red")
# mtext(expression(paste(phi," = 0")))
# text(1,0.9,"b)",cex=1.2)
# 
# plot(NA,NA,ylim=c(-1,1),xlim=c(0,20),xaxt="n",yaxt="n",xlab="",ylab="")
# axis(1, at=c(0,10,20), labels=NA)
# axis(2, at=c(-1,0,1), labels=NA)
# lines(tt[tt<=20],sig3,lwd=2)
# lines(tt[tt<=20],sig5,lwd=2,col="red")
# mtext(expression(paste(phi," = ",pi,"/2")))
# text(1,0.9,"c)",cex=1.2)
# 
# plot(NA,NA,ylim=c(-1,1),xlim=c(0,20),xaxt="n",yaxt="n",xlab="",ylab="")
# axis(1, at=c(0,10,20), labels=NA)
# axis(2, at=c(-1,0,1), labels=NA)
# lines(tt[tt<=20],sig3,lwd=2)
# lines(tt[tt<=20],sig6,lwd=2,col="red")
# mtext(expression(paste(phi," = ",pi)))
# text(1,0.9,"d)",cex=1.2)
# 
# 
# mtext("Time", 1, outer=T)
# mtext("Signal", 2, outer=T)
# 
# dev.off()

```

```{r summarize coherences, echo=TRUE, cache=FALSE}
#short timescales
hist(coh.chlaXaccndvi$accndvicoh.ts1, main="Accumulated NDVI, short timescales", xlab="Coherence", ylab="Frequency")
#hist(coh.chlaXmaxndvi$maxndvicoh.ts1, main="Maximum NDVI, short timescales", xlab="Coherence", ylab="Frequency")

quantile(coh.chlaXaccndvi$accndvicoh.ts1)
#quantile(coh.chlaXmaxndvi$maxndvicoh.ts1)

alpha=0.05
sum(coh.chlaXaccndvi$accndvip.ts1<alpha)/nrow(coh.chlaXaccndvi)
#sum(coh.chlaXmaxndvi$maxndvip.ts1<alpha)/nrow(coh.chlaXmaxndvi)

print(cbind(coh.chlaXaccndvi$lagoslakeid, coh.chlaXaccndvi$accndvip.ts1)[coh.chlaXaccndvi$accndvip.ts1<alpha,])
print(cbind(coh.chlaXaccndvi$lagoslakeid, coh.chlaXaccndvi$accndvip.ts2)[coh.chlaXaccndvi$accndvip.ts2<alpha,])

cor(coh.chlaXaccndvi$accndvicoh.ts1,coh.chlaXaccndvi$accndvicoh.ts2)

# print(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<alpha]/pi) #only pattern is that lakes don't lead the landscape
# print(coh.chlaXmaxndvi$maxndviphi.ts1[coh.chlaXmaxndvi$maxndvip.ts1<alpha]/pi)

phicls<-c(-1,-.75,-0.25,0.25,0.75,1)

# hist(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<0.2]/pi, main="Accumulated NDVI, short timescales", xlab="Phase (pi)", ylab="Frequency", breaks=phicls)
rose(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<0.3], unit="radian",
     breaks=seq(0,2*pi,length.out=16))
#hist(coh.chlaXmaxndvi$maxndviphi.ts1[coh.chlaXmaxndvi$maxndvip.ts1<0.2]/pi, main="Maximum NDVI, short timescales", xlab="Phase (pi)", ylab="Frequency", breaks=5)

#long timescales
hist(coh.chlaXaccndvi$accndvicoh.ts2, main="Accumulated NDVI, long timescales", xlab="Coherence", ylab="Frequency")
#hist(coh.chlaXmaxndvi$maxndvicoh.ts2, main="Maximum NDVI, long timescales", xlab="Coherence", ylab="Frequency")

quantile(coh.chlaXaccndvi$accndvicoh.ts2)
#quantile(coh.chlaXmaxndvi$maxndvicoh.ts2)

alpha=0.05
sum(coh.chlaXaccndvi$accndvip.ts2<alpha)/nrow(coh.chlaXaccndvi)
#sum(coh.chlaXmaxndvi$maxndvip.ts2<alpha)/nrow(coh.chlaXmaxndvi)

print(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<alpha]/pi)
#print(coh.chlaXmaxndvi$maxndviphi.ts2[coh.chlaXmaxndvi$maxndvip.ts2<alpha]/pi)

# hist(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<0.2]/pi, main="Accumulated NDVI, long timescales", xlab="Phase (pi)", ylab="Frequency", breaks=phicls)
rose(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<0.3], unit="radian",
     breaks=seq(0,2*pi,length.out=16))

#hist(coh.chlaXmaxndvi$maxndviphi.ts1[coh.chlaXmaxndvi$maxndvicoh.ts2>0.6]/pi, main="Maximum NDVI, short timescales", xlab="Phase (pi)", ylab="Frequency", breaks=5)
# 
# tiff("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig2_distributions.tif", units="in",
#      res=300, width=6.5, height=6.5)
# 
# par(mar=c(3,3,2,1),mgp=c(1.7,0.5,0),mfrow=c(2,2),cex.main=0.9)
# 
# hist(coh.chlaXaccndvi$accndvicoh.ts1, main="Short timescale coherence", xlab="Coherence", ylab="Frequency", col="lightgrey")
# text(par()$usr[1]+.05,0.95*par()$usr[4],"a)")
# hist(coh.chlaXaccndvi$accndvicoh.ts2, main="Long timescale coherence", xlab="Coherence", ylab="Frequency", col="lightgrey")
# text(par()$usr[1]+.05,0.95*par()$usr[4],"b)")
# 
# par(mar=c(1,1,2,1))
# rose(coh.chlaXaccndvi$accndviphi.ts1[coh.chlaXaccndvi$accndvip.ts1<0.3], unit="radian", col="lightgrey",
#      breaks=c(0,pi/4,pi/2,3*pi/4,pi,5*pi/4,3*pi/2,7*pi/4,2*pi), main="Short timescale phases",
#        at=c(0,pi/4,pi/2,3*pi/4,pi,-3*pi/4,-pi/2,-pi/4))
# text(0.9*par()$usr[1],0.95*par()$usr[4],"c)")
# rose(coh.chlaXaccndvi$accndviphi.ts2[coh.chlaXaccndvi$accndvip.ts2<0.3], unit="radian", col="lightgrey",
#      breaks=c(0,pi/4,pi/2,3*pi/4,pi,5*pi/4,3*pi/2,7*pi/4,2*pi), main="Long timescale phases",
#      at=c(0,pi/4,pi/2,3*pi/4,pi,-3*pi/4,-pi/2,-pi/4))
# text(0.9*par()$usr[1],0.95*par()$usr[4],"d)")
# 
# dev.off()

```

```{r mapping, echo=TRUE, cache=FALSE}

states<-readOGR("~/Box Sync/NSF EAGER Synchrony/Data/statesp020.shp")
getstates<-c("Minnesota", "Iowa", "Wisconsin", "Illinois", "Missouri", "Michigan", "Indiana", "Ohio", "Pennsylvania", "New York", "New Jersey", "Connecticut", "New Hampshire", "Rhode Island", "Massachusetts", "Vermont", "Maine")
lagosstates<-states[states@data$STATE %in% getstates,]

plot(lagosstates, main="Lakes selected for analysis")
points(analysislakes$lakeinfo$nhd_long, analysislakes$lakeinfo$nhd_lat, pch=16, cex=1, col="blue")


cohplotdata<-left_join(analysislakes$lakeinfo, coh.chlaXaccndvi, by="lagoslakeid")

pal<-viridis(100)

par(mar=c(1,0,2,0))

plot(lagosstates, main="Lakes by short timescale coherence")
par()$usr
points(cohplotdata$nhd_long, cohplotdata$nhd_lat, pch=16, cex=1, col=pal[round(cohplotdata$accndvicoh.ts1,2)*100])
colorbar.plot(x=mean(par("usr")[1:2]),y=par("usr")[3],strip=1:100,col=pal,horizontal = T)

plot(lagosstates, main="Lakes by long timescale coherence")
points(cohplotdata$nhd_long, cohplotdata$nhd_lat, pch=16, cex=1, col=pal[round(cohplotdata$accndvicoh.ts2,2)*100])
colorbar.plot(x=mean(par("usr")[1:2]),y=par("usr")[3],strip=1:100,col=pal,horizontal = T)


laymat=matrix(1,nrow=2,ncol=13)
laymat[2,]<-2
laymat[,13]<-3

# tiff("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig3_coherencemap.tif", units="in",
#      res=300, width=6.5, height=7.5)
# 
# layout(laymat)
# par(mar=c(0,0,1.5,0))
# 
# plot(lagosstates, main="Short timescale coherence")
# points(cohplotdata$nhd_long, cohplotdata$nhd_lat, pch=16, cex=1.5, col=pal[round(cohplotdata$accndvicoh.ts1,2)*100])
# text(0.99*par()$usr[1],0.99*par()$usr[4],"a)",cex=1.5)
# 
# plot(lagosstates, main="Long timescale coherence")
# points(cohplotdata$nhd_long, cohplotdata$nhd_lat, pch=16, cex=1.5, col=pal[round(cohplotdata$accndvicoh.ts2,2)*100])
# text(0.99*par()$usr[1],0.99*par()$usr[4],"b)",cex=1.5)
# 
# par(mar=c(5,1,5,1))
# image(matrix(1:100,nrow=1),col=pal,xaxt="n",yaxt="n")
# axis(2,at=seq(0,1,0.2))
# 
# dev.off()

```


```{r add vars for modelling, echo=TRUE, cache=FALSE}

#Need to add: depth, average growing season Chlorophyll-a, TSI(chla) categories, pct ag

#agriculture -- is 500m buffer best? Other options include 100m buffer (probably too small) and hu12 watershed
# pct.ag<-lagosne_select(table="buffer500m.lulc", vars=c("lagoslakeid","buffer500m_nlcd2001_pct_82","buffer500m_nlcd2006_pct_82","buffer500m_nlcd2011_pct_82"))
pct.ag<-lagosne_select(table="hu12.lulc", vars=c("hu12_zoneid","hu12_nlcd2001_pct_82","hu12_nlcd2006_pct_82","hu12_nlcd2011_pct_82"))
pct.ag<-pct.ag[pct.ag$hu12_zoneid %in% analysislakes$lakeinfo$hu12_zoneid,]
pct.ag.avg<-data.frame(hu12_zoneid=pct.ag$hu12_zoneid, pct.ag=rowMeans(pct.ag[,2:4]))

#Wetlands
pct.wetlands<-lagosne_select(table="hu12.lulc", vars=c(c("hu12_zoneid","hu12_nlcd2001_pct_90","hu12_nlcd2006_pct_90",
                                                         "hu12_nlcd2011_pct_90","hu12_nlcd2001_pct_95","hu12_nlcd2006_pct_95",
                                                         "hu12_nlcd2011_pct_95")))
pct.wetlands<-pct.wetlands[pct.wetlands$hu12_zoneid %in% analysislakes$lakeinfo$hu12_zoneid,]
pct.wetlands$sum2001<-rowSums(pct.wetlands[,c(2,5)])
pct.wetlands$sum2006<-rowSums(pct.wetlands[,c(3,6)])
pct.wetlands$sum2011<-rowSums(pct.wetlands[,c(4,7)])
pct.wetlands.avg<-data.frame(hu12_zoneid=pct.wetlands$hu12_zoneid, pct.wetlands=rowMeans(pct.wetlands[,8:10]))

#depth
depth<-lagosne_select(table="lakes_limno", vars=c("lagoslakeid","maxdepth"))
depth<-depth[depth$lagoslakeid %in% analysislakes$lakeinfo$lagoslakeid,] #use max depth because it's more complete

#growing season Chlorophyll-a
chla<-lagosne_select(table="epi_nutr", vars=c("lagoslakeid","samplemonth","chla"))
chla<-chla[chla$lagoslakeid %in% analysislakes$lakeinfo$lagoslakeid,]
gs.chla<-chla[chla$samplemonth %in% 5:9,]
avg.chla<-aggregate(chla ~ lagoslakeid, data=gs.chla, FUN=mean, na.rm=T)

#growing season DOC
doc<-lagosne_select(table="epi_nutr", vars=c("lagoslakeid","samplemonth","doc"))
doc<-doc[doc$lagoslakeid %in% analysislakes$lakeinfo$lagoslakeid,]
gs.doc<-doc[doc$samplemonth %in% 5:9,]
avg.doc<-aggregate(doc ~ lagoslakeid, data=gs.doc, FUN=mean, na.rm=T)

#Chlorophyll-a TSI class
#TSI(CHL) = 9.81 ln(CHL) + 30.6
tsi.chl<-data.frame(lagoslakeid=avg.chla$lagoslakeid, tsi=9.81 * log(avg.chla$chla) + 30.6)
tsi.chl$tsi.cat<-rep("lake",nrow(tsi.chl))

tsi.chl$tsi.cat[tsi.chl$tsi < 40]<-"oligotrophic"
tsi.chl$tsi.cat[tsi.chl$tsi >=40 & tsi.chl$tsi < 50]<-"mesotrophic"
tsi.chl$tsi.cat[tsi.chl$tsi >=50 & tsi.chl$tsi < 70]<-"eutrophic"
tsi.chl$tsi.cat[tsi.chl$tsi >= 70] <-"hypereutrophic"

#CV of terrestrial NDVI
cv.accndvi<-NULL
for(lake in 1:length(analysislakes$lakedata)){
  tmp<-analysislakes$lakedata[[lake]][rownames(analysislakes$lakedata[[lake]])=="accndvi",]
  cv.accndvi<-c(cv.accndvi, sd(tmp)/mean(tmp))  
 # rm(tmp)
}
cv.accndvi<-data.frame(lagoslakeid=as.numeric(names(analysislakes$lakedata)), cv.accndvi=cv.accndvi)

#mean precipitation
prcp.normal<-raster("~/Box Sync/NSF EAGER Synchrony/Data/PRISM Data/PRISM_ppt_30yr_normal_800mM2_annual_bil.bil")
lakepts<-SpatialPoints(coords=cbind(analysislakes$lakeinfo$nhd_long,analysislakes$lakeinfo$nhd_lat))
lake.prcp<-data.frame(lagoslakeid=analysislakes$lakeinfo$lagoslakeid, prcp.normal=raster::extract(prcp.normal,lakepts))

#huc2 and huc4 watershed codes
huc_codes<-read.csv("/Users/jonathanwalter/GitHub/AquaTerrSynch/AnalysisCode/match_huc_codes.csv", colClasses = 'character')

#state info
states<-lagosne_select(table="state", vars=c("state_zoneid","state_name"))

#shoreline development ratio
sdev<-analysislakes$lakeinfo$lake_perim_meters/(2*sqrt(pi*analysislakes$lakeinfo$lake_area_ha*10000))
shoredev<-data.frame(lagoslakeid=analysislakes$lakeinfo$lagoslakeid,shoredev=sdev)

predictors<-analysislakes$lakeinfo
predictors<-left_join(predictors, depth, by="lagoslakeid")
predictors<-left_join(predictors, pct.ag.avg, by="hu12_zoneid")
predictors<-left_join(predictors, pct.wetlands.avg, by="hu12_zoneid")
predictors<-left_join(predictors, avg.chla, by="lagoslakeid")
predictors<-left_join(predictors, tsi.chl, by="lagoslakeid")
predictors<-left_join(predictors, states, by="state_zoneid")
predictors<-left_join(predictors, cv.accndvi, by="lagoslakeid")
predictors<-left_join(predictors, avg.doc, by="lagoslakeid")
predictors<-left_join(predictors, lake.prcp, by="lagoslakeid")
predictors<-left_join(predictors, shoredev, by="lagoslakeid")
#predictors<-left_join(predictors, huc_codes, by="hu4_zoneid")

for(nn in 1:ncol(predictors)){
  
  if(is.factor(predictors[,nn])){
    predictors[,nn]<-factor(predictors[,nn])
  }
  
}
  
str(predictors)
hist(predictors$tslength)
hist(predictors$lake_area_ha)
hist(log10(predictors$lake_area_ha))
hist(predictors$lake_perim_meters)
hist(log10(predictors$lake_perim_meters))
table(predictors$nhd_fcode)
table(predictors$hu12_zoneid)
hist(predictors$elevation_m)
hist(predictors$maxdepth)
hist(log10(predictors$maxdepth))
hist(predictors$pct.ag)
hist(log10(predictors$pct.ag))
hist(predictors$chla)
hist(log10(predictors$chla))
hist(predictors$tsi)
table(predictors$tsi.cat)
hist(predictors$cv.accndvi)
hist(predictors$pct.wetlands)
hist(predictors$doc)
hist(predictors$prcp.normal)
hist(predictors$shoredev)

predictors$log10_lake_area_ha<-log10(predictors$lake_area_ha) #not necessary to transform with random forests
# predictors$log10_lake_perim_meters<-log10(predictors$lake_perim_meters)
# predictors$log10_maxdepth<-log10(predictors$maxdepth)
# predictors$log10_pct.ag<-log10(predictors$pct.ag+1)
# predictors$log10_chla<-log10(predictors$chla)

modvars.accndvi<-left_join(predictors, coh.chlaXaccndvi, by="lagoslakeid")
modvars.accndvi$nhd_ftype<-factor(modvars.accndvi$nhd_ftype)
modvars.accndvi$tsi.cat<-factor(modvars.accndvi$tsi.cat)
modvars.accndvi$tslength<-modvars.accndvi$end-modvars.accndvi$start + 1

modvars.accndvi<-modvars.accndvi[!is.na(modvars.accndvi$maxdepth),]
modvars.accndvi<-modvars.accndvi[!is.na(modvars.accndvi$pct.ag),]

modvars.accndvi.phist<-modvars.accndvi[modvars.accndvi$accndvip.ts1<0.3,]
modvars.accndvi.philt<-modvars.accndvi[modvars.accndvi$accndvip.ts2<0.3,]



```


```{r modellingCoherence, echo=TRUE, cache=FALSE}

# cforest.st<-partykit::cforest(accndvicoh.ts1 ~ lake_area_ha + lake_perim_meters + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + cv.accndvi, 
# #                     data=modvars.accndvi, ntree=20000)
# cforest.st<-party::cforest(accndvicoh.ts1 ~ shoredev + lake_area_ha +  maxdepth + pct.ag + chla + tsi.cat + 
#                              hu4_zoneid + cv.accndvi + pct.wetlands + doc + prcp.normal,
#                     data=modvars.accndvi, controls=cforest_control(ntree=80000))

lwgt<-modvars.accndvi$tslength/mean(modvars.accndvi$tslength)

gam.cohst<-gam(accndvicoh.ts1 ~ s(shoredev) + s(prcp.normal) + s(log10(lake_area_ha)) + s(pct.ag),  weights=lwgt, data=modvars.accndvi, 
               gamma=1.4, na.action = "na.fail")
#dredge.cohst<-dredge(gam.cohst, evaluate=TRUE, m.lim=c(0,5))
#importance(dredge.cohst)
#modavg.cohst<-model.avg(dredge.cohst, fit=T)
summary(gam.cohst)

plot(modvars.accndvi$accndvicoh.ts1,predict(gam.cohst))

topmod.cohst<-gam(accndvicoh.ts1 ~ s(shoredev,k=3) + s(log10(lake_area_ha),k=3) + s(prcp.normal,k=3) + s(pct.ag,k=3), data=modvars.accndvi,
                  gamma=1)
summary(topmod.cohst)


gam.cohlt<-gam(accndvicoh.ts2 ~ s(shoredev,k=3) + s(log10(lake_area_ha),k=3) +  s(maxdepth,k=3) + s(pct.ag,k=3) + 
                 s(chla,k=3) + tsi.cat + hu4_zoneid + s(cv.accndvi,k=3) + s(pct.wetlands,k=3) +  #removed doc because of NAs
                 s(prcp.normal,k=3), data=modvars.accndvi, gamma=1,na.action = "na.fail")
dredge.cohlt<-dredge(gam.cohlt, evaluate=TRUE, m.lim=c(0,5))
importance(dredge.cohlt)
modavg.cohlt<-model.avg(dredge.cohlt, fit=T)

plot(modvars.accndvi$accndvicoh.ts1,predict(modavg.cohlt))

topmod.cohlt<-gam(accndvicoh.ts1 ~ s(pct.wetlands,k=3) + s(cv.accndvi,k=3) + s(prcp.normal,k=3) + s(maxdepth,k=3), data=modvars.accndvi,
                  gamma=1)
summary(topmod.cohlt)




predcoh.st<-predict(cforest.st, newdata=modvars.accndvi,type="response")
#hist(predcoh.st)
#hist(modvars.accndvi$accndvicoh.ts1)
plot(predcoh.st, modvars.accndvi$accndvicoh.ts1, xlab="predicted", ylab="empirical", main="Coherence, short ts",
     xlim=c(0,1), ylim=c(0,1))
abline(a=0,b=1)
cor.test(predcoh.st,modvars.accndvi$accndvicoh.ts1)
varimp.coh.st<-varimp(cforest.st)
print(varimp.coh.st[order(varimp.coh.st, decreasing=T)])

pdp.shoredev.coh.st<-partial(cforest.st, pred.var="shoredev", train=modvars.accndvi, type="regression", plot=T)
pdp.prcp.coh.st<-partial(cforest.st, pred.var="prcp.normal", train=modvars.accndvi, type="regression", plot=T)
pdp.ag.coh.st<-partial(cforest.st, pred.var="pct.ag", train=modvars.accndvi, type="regression", plot=T)
pdp.maxdepth.coh.st<-partial(cforest.st, pred.var="maxdepth", train=modvars.accndvi, type="regression", plot=T)
pdp.lakearea.coh.st<-partial(cforest.st, pred.var="lake_area_ha", train=modvars.accndvi, type="regression", plot=T)
pdp.chla.coh.st<-partial(cforest.st, pred.var="chla", train=modvars.accndvi, type="regression", plot=T)
pdp.doc.coh.st<-partial(cforest.st, pred.var="doc", train=modvars.accndvi, type="regression", plot=T)
pdp.cv.coh.st<-partial(cforest.st, pred.var="cv.accndvi", train=modvars.accndvi, type="regression", plot=T)
pdp.wetlands.coh.st<-partial(cforest.st, pred.var="pct.wetlands", train=modvars.accndvi, type="regression", plot=T)
pdp.region.coh.st<-partial(cforest.st, pred.var="hu4_zoneid", train=modvars.accndvi, type="regression", plot=T)
pdp.tsi.coh.st<-partial(cforest.st, pred.var="tsi.cat", train=modvars.accndvi, type="regression", plot=T)

cforest.lt<-party::cforest(accndvicoh.ts2 ~ shoredev + lake_area_ha + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid 
                           + cv.accndvi+ pct.wetlands + doc + prcp.normal, 
                    data=modvars.accndvi, controls=cforest_control(ntree=80000))
predcoh.lt<-predict(cforest.lt, newdata=modvars.accndvi)
# hist(predcoh.lt)
# hist(modvars.accndvi$accndvicoh.ts2)
plot(predcoh.lt, modvars.accndvi$accndvicoh.ts2, xlab="predicted", ylab="empirical", main="Coherence, long st",
     xlim=c(0,1), ylim=c(0,1))
abline(a=0,b=1)
cor.test(predcoh.lt,modvars.accndvi$accndvicoh.ts2)
varimp.coh.lt<-varimp(cforest.lt)
print(varimp.coh.lt[order(varimp.coh.lt, decreasing=T)])


pdp.wetlands.coh.lt<-partial(cforest.lt, pred.var="pct.wetlands", train=modvars.accndvi, type="regression", plot=T)
pdp.cv.coh.lt<-partial(cforest.lt, pred.var="cv.accndvi", train=modvars.accndvi, type="regression", plot=T)
pdp.region.coh.lt<-partial(cforest.lt, pred.var="hu4_zoneid", train=modvars.accndvi, type="regression", plot=T)
pdp.tsi.coh.lt<-partial(cforest.lt, pred.var="tsi.cat", train=modvars.accndvi, type="regression", plot=T)
pdp.doc.coh.lt<-partial(cforest.lt, pred.var="doc", train=modvars.accndvi, type="regression", plot=T)
pdp.prcp.coh.lt<-partial(cforest.lt, pred.var="prcp.normal", train=modvars.accndvi, type="regression", plot=T)
pdp.lakearea.coh.lt<-partial(cforest.lt, pred.var="lake_area_ha", train=modvars.accndvi, type="regression", plot=T)
pdp.chla.coh.lt<-partial(cforest.lt, pred.var="chla", train=modvars.accndvi, type="regression", plot=T)
pdp.shoredev.coh.lt<-partial(cforest.lt, pred.var="shoredev", train=modvars.accndvi, type="regression", plot=T)
pdp.ag.coh.lt<-partial(cforest.lt, pred.var="pct.ag", train=modvars.accndvi, type="regression", plot=T)
pdp.maxdepth.coh.lt<-partial(cforest.lt, pred.var="maxdepth", train=modvars.accndvi, type="regression", plot=T)

```

```{r modellingPhase, echo=TRUE, cache=FALSE}

cforest.phi.st<-cforest(cos(accndviphi.ts1) ~ shoredev + lake_area_ha + maxdepth + pct.ag + chla + tsi.cat + 
                          hu4_zoneid + cv.accndvi+ pct.wetlands + doc + prcp.normal, 
                        data=modvars.accndvi.phist,controls=cforest_control(ntree=40000))
predphi.st<-predict(cforest.phi.st, newdata=modvars.accndvi.phist)
# hist(predphi.st)
# hist(cos(modvars.accndvi.phist$accndviphi.ts1))
plot(predphi.st, cos(modvars.accndvi.phist$accndviphi.ts1), xlab="predicted", ylab="empirical", main="cos(phase), short ts",
     xlim=c(-1,1), ylim=c(-1,1))
abline(a=0,b=1)
cor.test(predphi.st,cos(modvars.accndvi.phist$accndviphi.ts1))
varimp.phi.st<-varimp(cforest.phi.st)
print(varimp.phi.st[order(varimp.phi.st,decreasing=TRUE)])

pdp.maxdepth.phi.st<-partial(cforest.phi.st, pred.var="maxdepth", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.lakearea.phi.st<-partial(cforest.phi.st, pred.var="lake_area_ha", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.doc.phi.st<-partial(cforest.phi.st, pred.var="doc", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.cv.phi.st<-partial(cforest.phi.st, pred.var="cv.accndvi", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.shoredev.phi.st<-partial(cforest.phi.st, pred.var="shoredev", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.wetlands.phi.st<-partial(cforest.phi.st, pred.var="pct.wetlands", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.prcp.phi.st<-partial(cforest.phi.st, pred.var="prcp.normal", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.chla.phi.st<-partial(cforest.phi.st, pred.var="chla", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.ag.phi.st<-partial(cforest.phi.st, pred.var="pct.ag", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.tsi.phi.st<-partial(cforest.phi.st, pred.var="tsi.cat", train=modvars.accndvi.phist, type="regression", plot=T)
pdp.region.phi.st<-partial(cforest.phi.st, pred.var="hu4_zoneid", train=modvars.accndvi.phist, type="regression", plot=T)


cforest.phi.lt<-cforest(cos(accndviphi.ts2) ~ shoredev + lake_area_ha + maxdepth + pct.ag + chla + tsi.cat + hu4_zoneid + 
                          cv.accndvi + pct.wetlands + doc + prcp.normal, 
                        data=modvars.accndvi.philt,controls=cforest_control(ntree=40000))
predphi.lt<-predict(cforest.phi.lt, newdata=modvars.accndvi.philt)
# hist(predphi.lt)
# hist(cos(modvars.accndvi.philt$accndviphi.ts2))
plot(predphi.lt, cos(modvars.accndvi.philt$accndviphi.ts2), xlab="predicted", ylab="empirical", main="cos(phase), short ts",
     xlim=c(-1,1), ylim=c(-1,1))
abline(a=0,b=1)
cor.test(predphi.lt,cos(modvars.accndvi.philt$accndviphi.ts2))
varimp.phi.lt<-varimp(cforest.phi.lt)
print(varimp.phi.lt[order(varimp.phi.lt, decreasing=TRUE)])

pdp.region.phi.lt<-partial(cforest.phi.lt, pred.var="hu4_zoneid", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.lakearea.phi.lt<-partial(cforest.phi.lt, pred.var="lake_area_ha", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.prsp.phi.lt<-partial(cforest.phi.lt, pred.var="prcp.normal", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.wetlands.phi.lt<-partial(cforest.phi.lt, pred.var="pct.wetlands", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.doc.phi.lt<-partial(cforest.phi.lt, pred.var="doc", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.shoredev.phi.lt<-partial(cforest.phi.lt, pred.var="shoredev", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.chla.phi.lt<-partial(cforest.phi.lt, pred.var="chla", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.cv.phi.lt<-partial(cforest.phi.lt, pred.var="cv.accndvi", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.maxdepth.phi.lt<-partial(cforest.phi.lt, pred.var="maxdepth", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.ag.phi.lt<-partial(cforest.phi.lt, pred.var="pct.ag", train=modvars.accndvi.philt, type="regression", plot=T)
pdp.tsi.phi.lt<-partial(cforest.phi.lt, pred.var="tsi.cat", train=modvars.accndvi.philt, type="regression", plot=T)

save.image("~/Box Sync/NSF EAGER Synchrony/Data/RData files/ms1_analyses_complete_20190729.RData")

```
```{r plot predictions, echo=TRUE, cache=FALSE}

tiff("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/figS1_predvsemp.tif", units="in",
     res=300, width=6.5, height=6.5)

par(mar=c(2.5,2.5,1.5,1),mgp=c(1.7,0.5,0),mfrow=c(2,2),oma=c(1.2,1.2,0,0))

plot(predcoh.st, modvars.accndvi$accndvicoh.ts1, xlim=c(0,1), ylim=c(0,1), xlab="", ylab="")
mtext("Short timescale coherence",line=0.2)
abline(a=0,b=1)

plot(predcoh.lt, modvars.accndvi$accndvicoh.ts2, xlim=c(0,1), ylim=c(0,1), xlab="", ylab="")
mtext("Long timescale coherence",line=0.2)
abline(a=0,b=1)

plot(predphi.st, cos(modvars.accndvi.phist$accndviphi.ts1), xlim=c(-1,1), ylim=c(-1,1), xlab="", ylab="")
mtext("Short timescale cos(phase)",line=0.2)
abline(a=0,b=1)

plot(predphi.lt, cos(modvars.accndvi.philt$accndviphi.ts2), xlim=c(-1,1), ylim=c(-1,1), xlab="", ylab="")
mtext("Short timescale cos(phase)",line=0.2)
abline(a=0,b=1)

mtext("Predicted",1,outer=T)
mtext("Empirical",2,outer=T)

dev.off()


```

```{r varimp plotting, echo=TRUE, cache=FALSE}
#fig 4: variable importance in rank order

cleannames<-function(dirtynames){
  out<-NULL
  for(ii in 1:length(dirtynames)){
    if(dirtynames[ii]=="shoredev"){out<-c(out,"Shore. devel.")}
    if(dirtynames[ii]=="lake_area_ha"){out<-c(out,"Lake area")}
    if(dirtynames[ii]=="maxdepth"){out<-c(out,"Depth")}
    if(dirtynames[ii]=="pct.ag"){out<-c(out,"% agriculture")}
    if(dirtynames[ii]=="chla"){out<-c(out,"Chlorophyll-a")}
    if(dirtynames[ii]=="tsi.cat"){out<-c(out,"TSI")}
    if(dirtynames[ii]=="hu4_zoneid"){out<-c(out,"HU4 watershed")}
    if(dirtynames[ii]=="cv.accndvi"){out<-c(out,"CV(NDVI)")}
    if(dirtynames[ii]=="pct.wetlands"){out<-c(out,"% wetlands")}
    if(dirtynames[ii]=="doc"){out<-c(out,"DOC")}
    if(dirtynames[ii]=="prcp.normal"){out<-c(out,"Precipitation")}
  }
  return(out)
}

tiff("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig4_varimp.tif", units="in",
     res=300, width=6.5, height=6.5)

par(mar=c(6,3.8,1.5,1),mgp=c(1.7,0.5,0),mfrow=c(2,2),oma=c(0,1.2,0,0))

barplot(varimp.coh.st[order(varimp.coh.st,decreasing=T)], names.arg=cleannames(names(varimp.coh.st)[order(varimp.coh.st,decreasing=T)]), las=2,
        cex.names=0.9)
mtext("a) Short timescale coherence", line=0.25, cex=0.9)
barplot(varimp.coh.lt[order(varimp.coh.lt,decreasing=T)], names.arg=cleannames(names(varimp.coh.lt)[order(varimp.coh.lt,decreasing=T)]), las=2,
        cex.names=0.9)
mtext("b) Long timescale coherence", line=0.25, cex=0.9)
barplot(varimp.phi.st[order(varimp.phi.st,decreasing=T)], names.arg=cleannames(names(varimp.phi.st)[order(varimp.phi.st,decreasing=T)]), las=2,
        cex.names=0.9)
mtext("c) Short timescale phase", line=0.25, cex=0.9)
barplot(varimp.phi.lt[order(varimp.phi.lt,decreasing=T)], names.arg=cleannames(names(varimp.phi.lt)[order(varimp.phi.lt,decreasing=T)]), las=2,
        cex.names=0.9)
mtext("d) Long timescale phase", line=0.25, cex=0.9)
mtext("Variable importance",2,outer=T)

dev.off()
#fig 5: top variable importances (9 total)

states<-readOGR("~/Box Sync/NSF EAGER Synchrony/Data/statesp020.shp")
huc_bdys<-readOGR("~/Box Sync/NSF EAGER Synchrony/Data/huc4_watersheds.shp")
huc_codes<-read.csv("/Users/jonathanwalter/GitHub/AquaTerrSynch/AnalysisCode/match_huc_codes.csv", colClasses = 'character')
huc_codes<-huc_codes[huc_codes$hu4_zoneid %in% analysislakes$lakeinfo$hu4_zoneid,]

scale1_100<-function(x){
  x1<-x-min(x)+1/100
  x1<-round(x1/max(x1)*100)
  return(x1)
}

pdpdf.hu4.cohlt<-data.frame(hu4_zoneid=pdp.region.coh.lt$panel.args[[1]]$x, yhat=pdp.region.coh.lt$panel.args[[1]]$y)
pdpdf.hu4.cohlt<-left_join(pdpdf.hu4.cohlt, huc_codes)
huc_bdys1<-huc_bdys[huc_bdys$HUC4 %in% pdpdf.hu4.cohlt$huc4_code,]
huc_bdys1@data<-left_join(huc_bdys1@data, pdpdf.hu4.cohlt, by=c("HUC4"="huc4_code"))

pdpdf.hu4.philt<-data.frame(hu4_zoneid=pdp.region.phi.lt$panel.args[[1]]$x, yhat=pdp.region.phi.lt$panel.args[[1]]$y)
pdpdf.hu4.philt<-left_join(pdpdf.hu4.philt, huc_codes)
huc_bdys2<-huc_bdys[huc_bdys$HUC4 %in% pdpdf.hu4.philt$huc4_code,]
huc_bdys2@data<-left_join(huc_bdys2@data, pdpdf.hu4.philt, by=c("HUC4"="huc4_code"))

#make smaller images that we can insert into the main figure

png("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig5f_hu4_cohlt.png", units="in",
     res=300, width=6.5/3, height=8/3)
par(mar=c(0,0,0,0))
plot(huc_bdys1,bty="o",xlab="HU4 watershed", col=pal[scale1_100(huc_bdys1$yhat)])
lines(states)
par(fig=c(0.2,0.8,0.875,1), new=T,mar=c(.5,0,0.2,0), tcl=-0.15, mgp=c(1,0.2,0))
image(matrix(1:100,ncol=1),col=pal[1:100], xaxt="n", yaxt="n")
axis(1,at=c(0,0.25,0.5,0.75,1),labels=round(seq(min(huc_bdys1$yhat), max(huc_bdys1$yhat), length.out=5),2), cex=0.8)
dev.off()


png("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig5i_hu4_philt.png", units="in",
     res=300, width=6.5/3, height=8/3)
par(mar=c(0,0,0,0))
plot(huc_bdys2,bty="o",xlab="HU4 watershed", col=pal[scale1_100(huc_bdys2$yhat)])
lines(states)
par(fig=c(0.2,0.8,0.875,1), new=T,mar=c(.5,0,0.2,0), tcl=-0.15, mgp=c(1,0.2,0))
image(matrix(1:100,ncol=1),col=pal[1:100], xaxt="n", yaxt="n")
axis(1,at=c(0,0.25,0.5,0.75,1),labels=round(seq(min(huc_bdys2$yhat), max(huc_bdys2$yhat), length.out=5),2), cex=0.8)
dev.off()


laymat<-matrix(1:9,3,3,byrow=T)

library(png)
panel5f<-readPNG("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig5f_hu4_cohlt.png")
panel5i<-readPNG("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig5i_hu4_philt.png")

tiff("~/Box Sync/NSF EAGER Synchrony/Manuscripts/1_CoherenceSpatialVariation/fig5_partialeffects.tif", units="in",
     res=300, width=6.5, height=8)
layout(laymat)
par(mar=c(3.6,2,1.5,1),mgp=c(1.7,0.5,0),oma=c(0,1.5,0,0))
#cohst ~ shoredev, precip, % ag
plot(pdp.shoredev.coh.st$panel.args[[1]]$x, pdp.shoredev.coh.st$panel.args[[1]]$y, type="l", xlab="Shore. devel.", ylab="")
mtext("a) Short timesecale coherence", line=0.25, cex=0.7)
plot(pdp.prcp.coh.st$panel.args[[1]]$x, pdp.prcp.coh.st$panel.args[[1]]$y, type="l", xlab="Precipitation (mm/yr)", ylab="")
mtext("b) Short timesecale coherence", line=0.25, cex=0.7)
plot(pdp.ag.coh.st$panel.args[[1]]$x, pdp.ag.coh.st$panel.args[[1]]$y, type="l", xlab="Partial effect", ylab="")
mtext("c) Short timesecale coherence", line=0.25, cex=0.7)
#cohlt ~ pct.wetlands, cv(ndvi), hu4_zoneid
plot(pdp.wetlands.coh.lt$panel.args[[1]]$x, pdp.wetlands.coh.lt$panel.args[[1]]$y, type="l", xlab="% Wetlands", ylab="")
mtext("d) Long timescale coherence", line=0.25, cex=0.7)
plot(pdp.cv.coh.lt$panel.args[[1]]$x, pdp.cv.coh.lt$panel.args[[1]]$y, type="l", xlab="CV(NDVI)", ylab="")
mtext("e) Long timescale coherence", line=0.25, cex=0.7)
plot(NA,NA,xlim=c(0,1),ylim=c(0,1),xaxs="i",yaxs="i",ylab="",xlab="HU4 watershed",xaxt="n",yaxt="n",mgp=c(1,0.5,0))
rasterImage(image=panel5f,xleft=1e-2,ybottom=1e-2,xright=1-1e-2,ytop=1-1e-2)
mtext("f) Long timescale coherence", line=0.25, cex=0.7)
#phist ~ depth, lake area
plot(pdp.maxdepth.phi.st$panel.args[[1]]$x, pdp.maxdepth.phi.st$panel.args[[1]]$y, type="l", xlab="Depth (m)", ylab="")
mtext("g) Short timescale phase", line=0.25, cex=0.7)
plot(pdp.lakearea.phi.st$panel.args[[1]]$x, pdp.lakearea.phi.st$panel.args[[1]]$y, type="l", xlab="Lake area (ha)", ylab="")
mtext("h) Short timescale phase", line=0.25, cex=0.7)
#philt ~ hu4_zoneid
plot(NA,NA,xlim=c(0,1),ylim=c(0,1),xaxs="i",yaxs="i",ylab="",xlab="HU4 watershed", xaxt="n",yaxt="n",mgp=c(1,0.5,0))
rasterImage(image=panel5i,xleft=1e-2,ybottom=1e-2,xright=1-1e-2,ytop=1-1e-2)
mtext("i) Long timescale phase", line=0.25, cex=0.7)

mtext("Partial effect",side=2, outer=T, line=0.1)

dev.off()

```
